// Generated by CoffeeScript 1.6.3
var Comb, CsscombCompiler;

Comb = require('csscomb');

module.exports = CsscombCompiler = (function() {
  CsscombCompiler.prototype.brunchPlugin = true;

  CsscombCompiler.prototype.type = "stylesheet";

  CsscombCompiler.prototype.extension = "css";

  CsscombCompiler.prototype.pattern = /\.(?:css|scss|sass|less)$/;

  function CsscombCompiler(config) {
    var encoding, _ref;
    this.config = config;
    encoding = ((_ref = this.config.csscomb) != null ? _ref : {
      encoding: 'zen'
    }).encoding;
    this.comb = new Comb(encoding);
  }

  CsscombCompiler.prototype.compile = function(_arg, callback) {
    var data, map, path;
    data = _arg.data, path = _arg.path, map = _arg.map;
    try {
      this.comb.processPath(path);
    } catch (_error) {

    }
    return callback(error, {
      data: data,
      map: map
    });
  };

  return CsscombCompiler;

})();
